### ISSUE TITLE
wrong argument type Module (expected Class) (TypeError)

### ISSUE THREAD

**Issue by dvberkel** [dvberkel/space-invaders#1]
## Reproduction

```
> git checkout -b problem 33f09231f4d445d376545583168717a36b5f4c3e
> rvm use 1.9.2@invaders
> cucumber

wrong argument type Module (expected Class) (TypeError)
/home/user/space-invaders/src/gun.rb:6:in `<top (required)>' 
/home/user/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/user/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/user/space-invaders/src/space-invaders.rb:2:in `<top (required)>'
/home/user/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require' 
/home/user/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/user/space-invaders/features/step_definitions/space-invaders_steps.rb:1:in `<top (required)>' 
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/lib/cucumber/rb_support/rb_language.rb:129:in `load'
/home/user.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/lib/cucumber/rb_support/rb_language.rb:129:in `load_code_file'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/lib/cucumber/runtime/support_code.rb:171:in `load_file'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/lib/cucumber/runtime/support_code.rb:82:in `each'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/lib/cucumber/runtime.rb:174:in `load_step_definitions'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/lib/cucumber/runtime.rb:40:in `run!'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/lib/cucumber/cli/main.rb:43:in `execute!'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/lib/cucumber/cli/main.rb:20:in `execute'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/gems/cucumber-1.1.4/bin/cucumber:14:in `<top (required)>'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/bin/cucumber:19:in `load'
/home/user/.rvm/gems/ruby-1.9.2-p290@invaders/bin/cucumber:19:in `<main>'
```
## Expectation

A successful run of cucumber.
## Stumble block

I have no idea how to interpret or resolve the error `wrong argument type Module (expected Class) (TypeError)`.

**Comment by dvberkel** [comment]
The following [stackoverflow](http://stackoverflow.com/questions/6254496/is-it-possible-to-give-a-sub-module-the-same-name-as-a-top-level-class) issue describes a similar problem as found in this issue.

Maybe it can be of assistance in the resolution of the problem.

**Comment by dvberkel** [comment]
Because we are not working on space invaders any more, I am closing this issue
